apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  labels:             #labels should be same for selector and servcies
    app: go-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: anuragjosyula/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
