name: CI(continuous Integration)
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - 'helm/**'
    - 'k8s/**'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22.5
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Build
      run: go build -o go-web-app 

    - name: Test
      run: go test ./...

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run GolangCI-Lint #static code analysis
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.59.2

        
